[package]
name = "chromedriver-auto-update"
version = "0.1.0"
author = "licht.cui"
edition = "2021"

[dependencies]
regex = "1.10"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
toml = "0.8"
url = "2.5"
zip = "2.1"
