name: Feasibility

on:
  push:
    branches:
      - master

env:
  EXPECTED_VERSION: ChromeDriver 120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483})

jobs:
  mac-apple:
    name: mac-arm
    runs-on: macos-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --release
      - name: use
        run: ./target/release/chromedriver-update --browser-path="/Users/runner/hostedtoolcache/setup-chrome/chromium/120.0.6099.109/arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing" --driver-path="/Users/runner/hostedtoolcache/chromedriver"
      - name: check chromedriver version
        run: |
          CHROMEDRIVER_VERSION=$(/Users/runner/hostedtoolcache/chromedriver --version)
          echo "Expected: ${{ env.EXPECTED_VERSION }}"
          echo "Got: $CHROMEDRIVER_VERSION"
          if [ "$CHROMEDRIVER_VERSION" != "${{ env.EXPECTED_VERSION }}" ]; then
            echo "Chromedriver version is not as expected."
            exit 1
          else
            echo "Chromedriver version is as expected."
            exit 0
          fi

  mac-intel:
    name: mac-intel
    runs-on: macos-13
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --release
      - name: use
        run: ./target/release/chromedriver-update --browser-path="/Users/runner/hostedtoolcache/setup-chrome/chromium/120.0.6099.109/x64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing" --driver-path="/Users/runner/hostedtoolcache/chromedriver"
      - name: check chromedriver version
        run: |
          CHROMEDRIVER_VERSION=$(/Users/runner/hostedtoolcache/chromedriver --version)
          echo "Expected: ${{ env.EXPECTED_VERSION }}"
          echo "Got: $CHROMEDRIVER_VERSION"
          if [ "$CHROMEDRIVER_VERSION" != "${{ env.EXPECTED_VERSION }}" ]; then
            echo "Chromedriver version is not as expected."
            exit 1
          else
            echo "Chromedriver version is as expected."
            exit 0
          fi

  linux-x86:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --release
      - name: use
        run: ./target/release/chromedriver-update --browser-path="/opt/hostedtoolcache/setup-chrome/chromium/120.0.6099.109/x64/chrome" --driver-path="/opt/chromedriver"
      - name: check chromedriver version
        run: |
          CHROMEDRIVER_VERSION=$(/opt/chromedriver --version)
          echo "Expected: ${{ env.EXPECTED_VERSION }}"
          echo "Got: $CHROMEDRIVER_VERSION"
          if [ "$CHROMEDRIVER_VERSION" != "${{ env.EXPECTED_VERSION }}" ]; then
            echo "Chromedriver version is not as expected."
            exit 1
          else
            echo "Chromedriver version is as expected."
            exit 0
          fi

  windows:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --release
      - name: use
        run: |
          .\target\release\chromedriver-update.exe --browser-path="C:\hostedtoolcache\windows\setup-chrome\chromium\120.0.6099.109\x64\chrome.exe" --driver-path="C:\chromedriver.exe"
      - name: check chromedriver version
        shell: pwsh
        run: |
          $CHROMEDRIVER_PATH = "C:\chromedriver.exe"
          $CHROMEDRIVER_VERSION = & $CHROMEDRIVER_PATH --version
          Write-Host "Expected: ${{ env.EXPECTED_VERSION }}"
          Write-Host "Got: $CHROMEDRIVER_VERSION"
          if ($CHROMEDRIVER_VERSION -ne "${{ env.EXPECTED_VERSION }}") {
            Write-Host "Chromedriver version is not as expected."
            Exit 1
          } else {
            Write-Host "Chromedriver version is as expected."
            Exit 0
          }
