name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  mac:
    name: try build & run
    runs-on: macos-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - uses: actions/checkout@v4
      - name: setup rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Build
        run: cargo build --release
      - run: ls /Users/runner/hostedtoolcache/setup-chrome/chromium/120.0.6099.109/arm64

  linux:
    name: try build & run
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - uses: actions/checkout@v4
      - name: setup rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Build
        run: cargo build --release
      - run: ls /opt/hostedtoolcache/setup-chrome/chromium/120.0.6099.109/x64

  windows:
    name: try build & run
    runs-on: windows-latest
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - uses: actions/checkout@v4
      - name: setup rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Build
        run: cargo build --release
      - run: ls C:\hostedtoolcache\windows\setup-chrome\chromium\120.0.6099.109\x64
